### ISSUE TITLE
Shunting-yard SUBTRACTION operator associativity

### ISSUE THREAD

**Issue by gaborkolozsy** [nomemory/andreinc-site#1]
The Operator enum SUBTRACTION has RIGHT associativity. 
I think this is false by ie. `2 - 3 - 4`
It's returns with `2, 3, 4, -, - ` which is wrong. 
Expected: `2, 3, -, 4, -`

Change SUBTRACTION associativity to LEFT will be ok.

**Comment by nomemory** [comment]
@gaborkolozsy thanks for noticing this. I will do the change.
